import type { SeedProduct } from './products';

export type SeedMaterial = SeedProduct;

export const INITIAL_MATERIALS: SeedMaterial[] = [
  {
    id: 'PKG-TUB-BLK',
    name: 'Тубус чёрный (корпус)',
    name_ru: null,
    category: 'Упаковка',
    channel: 'internal',
    packaging: 'шт',
    weight_g: null,
    price_rrp: null,
    price_opt: null,
    price_opt_no_vat: null,
    vat_amount: null,
    discount_pct: null,
    warehouse: 'WH-02',
    barcode: null,
    is_material: true,
    is_active: null,
    notes: null
  },
  {
    id: 'PKG-TUB-LID',
    name: 'Крышка верхняя тубуса',
    name_ru: null,
    category: 'Упаковка',
    channel: 'internal',
    packaging: 'шт',
    weight_g: null,
    price_rrp: null,
    price_opt: null,
    price_opt_no_vat: null,
    vat_amount: null,
    discount_pct: null,
    warehouse: 'WH-02',
    barcode: null,
    is_material: true,
    is_active: null,
    notes: null
  },
  {
    id: 'PKG-TUB-BOT',
    name: 'Крышка-дно тубуса',
    name_ru: null,
    category: 'Упаковка',
    channel: 'internal',
    packaging: 'шт',
    weight_g: null,
    price_rrp: null,
    price_opt: null,
    price_opt_no_vat: null,
    vat_amount: null,
    discount_pct: null,
    warehouse: 'WH-02',
    barcode: null,
    is_material: true,
    is_active: null,
    notes: null
  },
  {
    id: 'PKG-STK-TUB',
    name: 'Стикер общий для тубуса (бренд)',
    name_ru: null,
    category: 'Упаковка',
    channel: 'internal',
    packaging: 'шт',
    weight_g: null,
    price_rrp: null,
    price_opt: null,
    price_opt_no_vat: null,
    vat_amount: null,
    discount_pct: null,
    warehouse: 'WH-02',
    barcode: null,
    is_material: true,
    is_active: null,
    notes: null
  },
  {
    id: 'PKG-STK-TYPE',
    name: 'Стикер тип чая (круглый)',
    name_ru: null,
    category: 'Упаковка',
    channel: 'internal',
    packaging: 'шт',
    weight_g: null,
    price_rrp: null,
    price_opt: null,
    price_opt_no_vat: null,
    vat_amount: null,
    discount_pct: null,
    warehouse: 'WH-02',
    barcode: null,
    is_material: true,
    is_active: null,
    notes: null
  },
  {
    id: 'PKG-STK-VAR',
    name: 'Стикер описание сорта (именной)',
    name_ru: null,
    category: 'Упаковка',
    channel: 'internal',
    packaging: 'шт',
    weight_g: null,
    price_rrp: null,
    price_opt: null,
    price_opt_no_vat: null,
    vat_amount: null,
    discount_pct: null,
    warehouse: 'WH-02',
    barcode: null,
    is_material: true,
    is_active: null,
    notes: null
  },
  {
    id: 'PKG-BAG-7G',
    name: 'Прозрачный порционный пакетик 7г',
    name_ru: null,
    category: 'Упаковка',
    channel: 'internal',
    packaging: 'шт',
    weight_g: null,
    price_rrp: null,
    price_opt: null,
    price_opt_no_vat: null,
    vat_amount: null,
    discount_pct: null,
    warehouse: 'WH-02',
    barcode: null,
    is_material: true,
    is_active: null,
    notes: null
  },
  {
    id: 'PKG-ZIP-210',
    name: 'Зип-лок пакет 210г (B2B бар)',
    name_ru: null,
    category: 'Упаковка',
    channel: 'internal',
    packaging: 'шт',
    weight_g: null,
    price_rrp: null,
    price_opt: null,
    price_opt_no_vat: null,
    vat_amount: null,
    discount_pct: null,
    warehouse: 'WH-02',
    barcode: null,
    is_material: true,
    is_active: null,
    notes: null
  },
  {
    id: 'PKG-ZIP-28',
    name: 'Зип-лок пакет 28г (витрина/сайт)',
    name_ru: null,
    category: 'Упаковка',
    channel: 'internal',
    packaging: 'шт',
    weight_g: null,
    price_rrp: null,
    price_opt: null,
    price_opt_no_vat: null,
    vat_amount: null,
    discount_pct: null,
    warehouse: 'WH-02',
    barcode: null,
    is_material: true,
    is_active: null,
    notes: null
  },
];

