export type SeedProduct = {
  id: string;
  name: string;
  name_ru?: string | null;
  category: string;
  channel: string;
  packaging: string;
  weight_g?: number | null;
  price_rrp?: number | null;
  price_opt?: number | null;
  price_opt_no_vat?: number | null;
  vat_amount?: number | null;
  discount_pct?: number | null;
  warehouse: string;
  barcode?: string | null;
  is_material?: boolean | null;
  is_active?: boolean | null;
  notes?: string | null;
};

export const INITIAL_PRODUCTS: SeedProduct[] = [
  // === ЧАЙ · КАНАЛ B2B БАР · Тубус 210г / Зип-лок 210г ===
  {
    id: 'GF-W-BMD210',
    name: 'Bai mu dan',
    name_ru: null,
    category: 'Белый чай',
    channel: 'B2B Бар',
    packaging: 'Тубус 210г / Зип-лок 210г',
    weight_g: 210,
    price_rrp: 3990,
    price_opt: 2992.5,
    price_opt_no_vat: 2493.75,
    vat_amount: 498.75,
    discount_pct: 0.25,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  {
    id: 'FJN-W-BMDR210',
    name: 'Bai mu dan with Rose',
    name_ru: null,
    category: 'Белый чай',
    channel: 'B2B Бар',
    packaging: 'Тубус 210г / Зип-лок 210г',
    weight_g: 210,
    price_rrp: 4200,
    price_opt: 3150,
    price_opt_no_vat: 2625,
    vat_amount: 525,
    discount_pct: 0.25,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  {
    id: 'GF-G-JG210',
    name: 'Jasmine Green Beverage',
    name_ru: null,
    category: 'Зелёный чай',
    channel: 'B2B Бар',
    packaging: 'Тубус 210г / Зип-лок 210г',
    weight_g: 210,
    price_rrp: 2940,
    price_opt: 2205,
    price_opt_no_vat: 1837.5,
    vat_amount: 367.5,
    discount_pct: 0.25,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  {
    id: 'CHC-G-GP210',
    name: 'Gunpowder',
    name_ru: null,
    category: 'Зелёный чай',
    channel: 'B2B Бар',
    packaging: 'Тубус 210г / Зип-лок 210г',
    weight_g: 210,
    price_rrp: 3675,
    price_opt: 2756.25,
    price_opt_no_vat: 2296.875,
    vat_amount: 459.375,
    discount_pct: 0.25,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  {
    id: 'GF-G-SN210',
    name: 'Sencha',
    name_ru: null,
    category: 'Зелёный чай',
    channel: 'B2B Бар',
    packaging: 'Тубус 210г / Зип-лок 210г',
    weight_g: 210,
    price_rrp: 2520,
    price_opt: 1890,
    price_opt_no_vat: 1575,
    vat_amount: 315,
    discount_pct: 0.25,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  {
    id: 'GF-G-MF210',
    name: 'Green Mao Feng',
    name_ru: null,
    category: 'Зелёный чай',
    channel: 'B2B Бар',
    packaging: 'Тубус 210г / Зип-лок 210г',
    weight_g: 210,
    price_rrp: 3465,
    price_opt: 2598.75,
    price_opt_no_vat: 2165.625,
    vat_amount: 433.125,
    discount_pct: 0.25,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  {
    id: 'GF-G-LJ210A',
    name: 'Long Jing A',
    name_ru: null,
    category: 'Зелёный чай',
    channel: 'B2B Бар',
    packaging: 'Тубус 210г / Зип-лок 210г',
    weight_g: 210,
    price_rrp: 6930,
    price_opt: 5197.5,
    price_opt_no_vat: 4331.25,
    vat_amount: 866.25,
    discount_pct: 0.25,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  {
    id: 'GF-G-DP210',
    name: 'Dragon pearl',
    name_ru: null,
    category: 'Зелёный чай',
    channel: 'B2B Бар',
    packaging: 'Тубус 210г / Зип-лок 210г',
    weight_g: 210,
    price_rrp: 6300,
    price_opt: 4725,
    price_opt_no_vat: 3937.5,
    vat_amount: 787.5,
    discount_pct: 0.25,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  {
    id: 'CHC-G-GNM210',
    name: 'Genmaicha',
    name_ru: null,
    category: 'Зелёный чай',
    channel: 'B2B Бар',
    packaging: 'Тубус 210г / Зип-лок 210г',
    weight_g: 210,
    price_rrp: 2880,
    price_opt: 2160,
    price_opt_no_vat: 1800,
    vat_amount: 360,
    discount_pct: 0.25,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  {
    id: 'GF-B-KM210',
    name: 'Keemum',
    name_ru: null,
    category: 'Красный/Чёрный',
    channel: 'B2B Бар',
    packaging: 'Тубус 210г / Зип-лок 210г',
    weight_g: 210,
    price_rrp: 3045,
    price_opt: 2283.75,
    price_opt_no_vat: 1903.125,
    vat_amount: 380.625,
    discount_pct: 0.25,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  {
    id: 'GF-B-ASB210',
    name: 'Assam Black Tea TFP',
    name_ru: null,
    category: 'Красный/Чёрный',
    channel: 'B2B Бар',
    packaging: 'Тубус 210г / Зип-лок 210г',
    weight_g: 210,
    price_rrp: 3570,
    price_opt: 2677.5,
    price_opt_no_vat: 2231.25,
    vat_amount: 446.25,
    discount_pct: 0.25,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  {
    id: 'GF-B-LS210',
    name: 'Lapsang Soushong Pine',
    name_ru: null,
    category: 'Красный/Чёрный',
    channel: 'B2B Бар',
    packaging: 'Тубус 210г / Зип-лок 210г',
    weight_g: 210,
    price_rrp: 3675,
    price_opt: 2756.25,
    price_opt_no_vat: 2296.875,
    vat_amount: 459.375,
    discount_pct: 0.25,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  {
    id: 'GF-B-EG210',
    name: 'Earl Grey',
    name_ru: null,
    category: 'Красный/Чёрный',
    channel: 'B2B Бар',
    packaging: 'Тубус 210г / Зип-лок 210г',
    weight_g: 210,
    price_rrp: 3675,
    price_opt: 2756.25,
    price_opt_no_vat: 2296.875,
    vat_amount: 459.375,
    discount_pct: 0.25,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  {
    id: 'GF-B-DHG210',
    name: 'Dian Hong A',
    name_ru: null,
    category: 'Красный/Чёрный',
    channel: 'B2B Бар',
    packaging: 'Тубус 210г / Зип-лок 210г',
    weight_g: 210,
    price_rrp: 5040,
    price_opt: 3780,
    price_opt_no_vat: 3150,
    vat_amount: 630,
    discount_pct: 0.25,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  {
    id: 'CHC-B-YU210',
    name: 'Yunnan black tea',
    name_ru: null,
    category: 'Красный/Чёрный',
    channel: 'B2B Бар',
    packaging: 'Тубус 210г / Зип-лок 210г',
    weight_g: 210,
    price_rrp: 3675,
    price_opt: 2756.25,
    price_opt_no_vat: 2296.875,
    vat_amount: 459.375,
    discount_pct: 0.25,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  {
    id: 'GF-G-TG210',
    name: 'Tieguanyin',
    name_ru: null,
    category: 'Улун',
    channel: 'B2B Бар',
    packaging: 'Тубус 210г / Зип-лок 210г',
    weight_g: 210,
    price_rrp: 3675,
    price_opt: 2756.25,
    price_opt_no_vat: 2296.875,
    vat_amount: 459.375,
    discount_pct: 0.25,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  {
    id: 'FJN-G-GO210',
    name: 'Ginseng Oolong',
    name_ru: null,
    category: 'Улун',
    channel: 'B2B Бар',
    packaging: 'Тубус 210г / Зип-лок 210г',
    weight_g: 210,
    price_rrp: 4200,
    price_opt: 3150,
    price_opt_no_vat: 2625,
    vat_amount: 525,
    discount_pct: 0.25,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  {
    id: 'FJN-B-DHP210',
    name: 'Da Hong Pao',
    name_ru: null,
    category: 'Улун',
    channel: 'B2B Бар',
    packaging: 'Тубус 210г / Зип-лок 210г',
    weight_g: 210,
    price_rrp: 4305,
    price_opt: 3228.75,
    price_opt_no_vat: 2690.625,
    vat_amount: 538.125,
    discount_pct: 0.25,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  {
    id: 'GF-G-MO210',
    name: 'Milky Oolong',
    name_ru: null,
    category: 'Улун',
    channel: 'B2B Бар',
    packaging: 'Тубус 210г / Зип-лок 210г',
    weight_g: 210,
    price_rrp: 3675,
    price_opt: 2756.25,
    price_opt_no_vat: 2296.875,
    vat_amount: 459.375,
    discount_pct: 0.25,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  {
    id: 'FJN-B-MPT50-10',
    name: 'Golden Tocha Round Pu Erh',
    name_ru: null,
    category: 'Пу Эр',
    channel: 'B2B Бар',
    packaging: 'Тубус 210г / Зип-лок 210г',
    weight_g: 100,
    price_rrp: 2000,
    price_opt: 1500,
    price_opt_no_vat: 1250,
    vat_amount: 250,
    discount_pct: 0.25,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  {
    id: 'GF-G-DP25-5-B',
    name: 'Rice Pu Erh Toucha (бар)',
    name_ru: null,
    category: 'Пу Эр',
    channel: 'B2B Бар',
    packaging: 'Тубус 210г / Зип-лок 210г',
    weight_g: 100,
    price_rrp: 2200,
    price_opt: 1650,
    price_opt_no_vat: 1375,
    vat_amount: 275,
    discount_pct: 0.25,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  {
    id: 'GF-B-GAB210',
    name: 'Gaba Oolong',
    name_ru: null,
    category: 'Технологичный',
    channel: 'B2B Бар',
    packaging: 'Тубус 210г / Зип-лок 210г',
    weight_g: 210,
    price_rrp: 7140,
    price_opt: 5355,
    price_opt_no_vat: 4462.5,
    vat_amount: 892.5,
    discount_pct: 0.25,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  {
    id: 'FJN-G-MXF210',
    name: 'Fresh Air Fruit Mix',
    name_ru: null,
    category: 'Less Tea',
    channel: 'B2B Бар',
    packaging: 'Тубус 210г / Зип-лок 210г',
    weight_g: 210,
    price_rrp: 4200,
    price_opt: 3150,
    price_opt_no_vat: 2625,
    vat_amount: 525,
    discount_pct: 0.25,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  {
    id: 'FJN-G-YGT210',
    name: 'Yoga Tea',
    name_ru: null,
    category: 'Less Tea',
    channel: 'B2B Бар',
    packaging: 'Тубус 210г / Зип-лок 210г',
    weight_g: 210,
    price_rrp: 5040,
    price_opt: 3780,
    price_opt_no_vat: 3150,
    vat_amount: 630,
    discount_pct: 0.25,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  {
    id: 'FJN-G-CLD210',
    name: 'Chinese Lovers Dreams',
    name_ru: null,
    category: 'Less Tea',
    channel: 'B2B Бар',
    packaging: 'Тубус 210г / Зип-лок 210г',
    weight_g: 210,
    price_rrp: 5040,
    price_opt: 3780,
    price_opt_no_vat: 3150,
    vat_amount: 630,
    discount_pct: 0.25,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  // === ЧАЙ · B2C / B2B2C / E-COMMERCE · Зип-лок 28г ===
  {
    id: 'GF-W-BMD28-AA',
    name: 'Bai mu dan АА',
    name_ru: null,
    category: 'Белый чай',
    channel: 'B2C / B2B2C / E-com',
    packaging: 'Зип-лок 28г',
    weight_g: 28,
    price_rrp: 672,
    price_opt: 504,
    price_opt_no_vat: 420,
    vat_amount: 84,
    discount_pct: 0.25,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  {
    id: 'GF-W-BMD28',
    name: 'Bai mu dan',
    name_ru: null,
    category: 'Белый чай',
    channel: 'B2C / B2B2C / E-com',
    packaging: 'Зип-лок 28г',
    weight_g: 28,
    price_rrp: 532,
    price_opt: 399,
    price_opt_no_vat: 332.5,
    vat_amount: 66.5,
    discount_pct: 0.25,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  {
    id: 'FJN-W-BMDR28',
    name: 'Bai mu dan with Rose',
    name_ru: null,
    category: 'Белый чай',
    channel: 'B2C / B2B2C / E-com',
    packaging: 'Зип-лок 28г',
    weight_g: 28,
    price_rrp: 560,
    price_opt: 420,
    price_opt_no_vat: 350,
    vat_amount: 70,
    discount_pct: 0.25,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  {
    id: 'GF-G-JXH28',
    name: 'Jasmine Xiang Hao',
    name_ru: null,
    category: 'Зелёный чай',
    channel: 'B2C / B2B2C / E-com',
    packaging: 'Зип-лок 28г',
    weight_g: 28,
    price_rrp: 490,
    price_opt: 367.5,
    price_opt_no_vat: 306.25,
    vat_amount: 61.25,
    discount_pct: 0.25,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  {
    id: 'GF-G-JG28',
    name: 'Jasmine Green Beverage',
    name_ru: null,
    category: 'Зелёный чай',
    channel: 'B2C / B2B2C / E-com',
    packaging: 'Зип-лок 28г',
    weight_g: 28,
    price_rrp: 420,
    price_opt: 315,
    price_opt_no_vat: 262.5,
    vat_amount: 52.5,
    discount_pct: 0.25,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  {
    id: 'CHC-G-GP28',
    name: 'Gunpowder',
    name_ru: null,
    category: 'Зелёный чай',
    channel: 'B2C / B2B2C / E-com',
    packaging: 'Зип-лок 28г',
    weight_g: 28,
    price_rrp: 490,
    price_opt: 367.5,
    price_opt_no_vat: 306.25,
    vat_amount: 61.25,
    discount_pct: 0.25,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  {
    id: 'GF-G-SN28',
    name: 'Sencha',
    name_ru: null,
    category: 'Зелёный чай',
    channel: 'B2C / B2B2C / E-com',
    packaging: 'Зип-лок 28г',
    weight_g: 28,
    price_rrp: 340,
    price_opt: 255,
    price_opt_no_vat: 212.5,
    vat_amount: 42.5,
    discount_pct: 0.25,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  {
    id: 'GF-G-MF28',
    name: 'Green Mao Feng',
    name_ru: null,
    category: 'Зелёный чай',
    channel: 'B2C / B2B2C / E-com',
    packaging: 'Зип-лок 28г',
    weight_g: 28,
    price_rrp: 460,
    price_opt: 345,
    price_opt_no_vat: 287.5,
    vat_amount: 57.5,
    discount_pct: 0.25,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  {
    id: 'GF-G-LJ28A',
    name: 'Long Jing A',
    name_ru: null,
    category: 'Зелёный чай',
    channel: 'B2C / B2B2C / E-com',
    packaging: 'Зип-лок 28г',
    weight_g: 28,
    price_rrp: 924,
    price_opt: 693,
    price_opt_no_vat: 577.5,
    vat_amount: 115.5,
    discount_pct: 0.25,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  {
    id: 'GF-G-DP28',
    name: 'Dragon pearl',
    name_ru: null,
    category: 'Зелёный чай',
    channel: 'B2C / B2B2C / E-com',
    packaging: 'Зип-лок 28г',
    weight_g: 28,
    price_rrp: 840,
    price_opt: 630,
    price_opt_no_vat: 525,
    vat_amount: 105,
    discount_pct: 0.25,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  {
    id: 'CHC-G-GNM28',
    name: 'Genmaicha',
    name_ru: null,
    category: 'Зелёный чай',
    channel: 'B2C / B2B2C / E-com',
    packaging: 'Зип-лок 28г',
    weight_g: 28,
    price_rrp: 448,
    price_opt: 336,
    price_opt_no_vat: 280,
    vat_amount: 56,
    discount_pct: 0.25,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  {
    id: 'GF-B-KM28',
    name: 'Keemum',
    name_ru: null,
    category: 'Красный/Чёрный',
    channel: 'B2C / B2B2C / E-com',
    packaging: 'Зип-лок 28г',
    weight_g: 28,
    price_rrp: 406,
    price_opt: 304.5,
    price_opt_no_vat: 253.75,
    vat_amount: 50.75,
    discount_pct: 0.25,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  {
    id: 'GF-B-BS28',
    name: 'Black Snail',
    name_ru: null,
    category: 'Красный/Чёрный',
    channel: 'B2C / B2B2C / E-com',
    packaging: 'Зип-лок 28г',
    weight_g: 28,
    price_rrp: 532,
    price_opt: 399,
    price_opt_no_vat: 332.5,
    vat_amount: 66.5,
    discount_pct: 0.25,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  {
    id: 'GF-B-ASB28',
    name: 'Assam Black Tea TFP',
    name_ru: null,
    category: 'Красный/Чёрный',
    channel: 'B2C / B2B2C / E-com',
    packaging: 'Зип-лок 28г',
    weight_g: 28,
    price_rrp: 476,
    price_opt: 357,
    price_opt_no_vat: 297.5,
    vat_amount: 59.5,
    discount_pct: 0.25,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  {
    id: 'GF-B-EG28',
    name: 'Earl Grey',
    name_ru: null,
    category: 'Красный/Чёрный',
    channel: 'B2C / B2B2C / E-com',
    packaging: 'Зип-лок 28г',
    weight_g: 28,
    price_rrp: 490,
    price_opt: 367.5,
    price_opt_no_vat: 306.25,
    vat_amount: 61.25,
    discount_pct: 0.25,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  {
    id: 'GF-B-LS28',
    name: 'Lapsang Soushong Pine',
    name_ru: null,
    category: 'Красный/Чёрный',
    channel: 'B2C / B2B2C / E-com',
    packaging: 'Зип-лок 28г',
    weight_g: 28,
    price_rrp: 490,
    price_opt: 367.5,
    price_opt_no_vat: 306.25,
    vat_amount: 61.25,
    discount_pct: 0.25,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  {
    id: 'FJN-B-SLPS28-A',
    name: 'Lapsang Soushong Smoked Plum',
    name_ru: null,
    category: 'Красный/Чёрный',
    channel: 'B2C / B2B2C / E-com',
    packaging: 'Зип-лок 28г',
    weight_g: 28,
    price_rrp: 672,
    price_opt: 504,
    price_opt_no_vat: 420,
    vat_amount: 84,
    discount_pct: 0.25,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  {
    id: 'GF-B-DHG28',
    name: 'Dian Hong',
    name_ru: null,
    category: 'Красный/Чёрный',
    channel: 'B2C / B2B2C / E-com',
    packaging: 'Зип-лок 28г',
    weight_g: 28,
    price_rrp: 672,
    price_opt: 504,
    price_opt_no_vat: 420,
    vat_amount: 84,
    discount_pct: 0.25,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  {
    id: 'CHC-B-YU28',
    name: 'Yunnan black tea',
    name_ru: null,
    category: 'Красный/Чёрный',
    channel: 'B2C / B2B2C / E-com',
    packaging: 'Зип-лок 28г',
    weight_g: 28,
    price_rrp: 490,
    price_opt: 367.5,
    price_opt_no_vat: 306.25,
    vat_amount: 61.25,
    discount_pct: 0.25,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  {
    id: 'GF-G-TG28',
    name: 'Tieguanyin',
    name_ru: null,
    category: 'Улун',
    channel: 'B2C / B2B2C / E-com',
    packaging: 'Зип-лок 28г',
    weight_g: 28,
    price_rrp: 490,
    price_opt: 367.5,
    price_opt_no_vat: 306.25,
    vat_amount: 61.25,
    discount_pct: 0.25,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  {
    id: 'FJN-B-OLTG28-AAA',
    name: '30-year-old Tieguanyin',
    name_ru: null,
    category: 'Улун',
    channel: 'B2C / B2B2C / E-com',
    packaging: 'Зип-лок 28г',
    weight_g: 28,
    price_rrp: 1680,
    price_opt: 1260,
    price_opt_no_vat: 1050,
    vat_amount: 210,
    discount_pct: 0.25,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  {
    id: 'FJN-B-DHP28',
    name: 'Da Hong Pao',
    name_ru: null,
    category: 'Улун',
    channel: 'B2C / B2B2C / E-com',
    packaging: 'Зип-лок 28г',
    weight_g: 28,
    price_rrp: 574,
    price_opt: 430.5,
    price_opt_no_vat: 358.75,
    vat_amount: 71.75,
    discount_pct: 0.25,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  {
    id: 'FJN-B-DHP28-AA',
    name: 'Da Hong Pao AA',
    name_ru: null,
    category: 'Улун',
    channel: 'B2C / B2B2C / E-com',
    packaging: 'Зип-лок 28г',
    weight_g: 28,
    price_rrp: 930,
    price_opt: 697.5,
    price_opt_no_vat: 581.25,
    vat_amount: 116.25,
    discount_pct: 0.25,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  {
    id: 'FJN-G-GO28',
    name: 'Ginseng Oolong',
    name_ru: null,
    category: 'Улун',
    channel: 'B2C / B2B2C / E-com',
    packaging: 'Зип-лок 28г',
    weight_g: 28,
    price_rrp: 560,
    price_opt: 420,
    price_opt_no_vat: 350,
    vat_amount: 70,
    discount_pct: 0.25,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  {
    id: 'FJN-G-MO28-AA',
    name: 'Milky Oolong',
    name_ru: null,
    category: 'Улун',
    channel: 'B2C / B2B2C / E-com',
    packaging: 'Зип-лок 28г',
    weight_g: 28,
    price_rrp: 480,
    price_opt: 360,
    price_opt_no_vat: 300,
    vat_amount: 60,
    discount_pct: 0.25,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  {
    id: 'FJN-PU-S28',
    name: 'Pu Erh Broken Silver Tea Stone',
    name_ru: null,
    category: 'Пу Эр',
    channel: 'B2C / B2B2C / E-com',
    packaging: 'Зип-лок 28г',
    weight_g: 28,
    price_rrp: 620,
    price_opt: 465,
    price_opt_no_vat: 387.5,
    vat_amount: 77.5,
    discount_pct: 0.25,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  {
    id: 'CHC-PU-MPC25-5',
    name: 'Golden Tocha Round Pu Erh 5g',
    name_ru: null,
    category: 'Пу Эр',
    channel: 'B2C / B2B2C / E-com',
    packaging: 'Зип-лок 25г',
    weight_g: 25,
    price_rrp: 500,
    price_opt: 375,
    price_opt_no_vat: 312.5,
    vat_amount: 62.5,
    discount_pct: 0.25,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  {
    id: 'CHC-PU-FTN100',
    name: 'Fermented Puer Tuocha Nest 100g',
    name_ru: null,
    category: 'Пу Эр',
    channel: 'B2C / B2B2C / E-com',
    packaging: 'Без переупаковки',
    weight_g: 100,
    price_rrp: 2650,
    price_opt: 1987.5,
    price_opt_no_vat: 1656.25,
    vat_amount: 331.25,
    discount_pct: 0.25,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: 'Без упак.'
  },
  {
    id: 'CHC-PU-MPC35-5',
    name: 'Banzhang Mini Pu Erh Cake 7g',
    name_ru: null,
    category: 'Пу Эр',
    channel: 'B2C / B2B2C / E-com',
    packaging: 'Зип-лок 35г',
    weight_g: 35,
    price_rrp: 1150,
    price_opt: 862.5,
    price_opt_no_vat: 718.75,
    vat_amount: 143.75,
    discount_pct: 0.25,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  {
    id: 'CHC-PU-RS10',
    name: 'Puer Chagao Resin Round 1g',
    name_ru: null,
    category: 'Пу Эр',
    channel: 'B2C / B2B2C / E-com',
    packaging: 'Зип-лок 10г',
    weight_g: 10,
    price_rrp: 520,
    price_opt: 390,
    price_opt_no_vat: 325,
    vat_amount: 65,
    discount_pct: 0.25,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  {
    id: 'CHC-PU-RR10',
    name: 'Puer Chagao Resin Square 1g',
    name_ru: null,
    category: 'Пу Эр',
    channel: 'B2C / B2B2C / E-com',
    packaging: 'Зип-лок 10г',
    weight_g: 10,
    price_rrp: 520,
    price_opt: 390,
    price_opt_no_vat: 325,
    vat_amount: 65,
    discount_pct: 0.25,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  {
    id: 'CHC-B-RS20BX',
    name: 'Puer Chagao Rice Resin Round Box',
    name_ru: null,
    category: 'Пу Эр',
    channel: 'B2C / B2B2C / E-com',
    packaging: 'Зип-лок 20г',
    weight_g: 20,
    price_rrp: 1100,
    price_opt: 825,
    price_opt_no_vat: 687.5,
    vat_amount: 137.5,
    discount_pct: 0.25,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  {
    id: 'CHC-B-PUL28',
    name: 'Pu Erh Laochatou',
    name_ru: null,
    category: 'Пу Эр',
    channel: 'B2C / B2B2C / E-com',
    packaging: 'Зип-лок 28г',
    weight_g: 28,
    price_rrp: 756,
    price_opt: 567,
    price_opt_no_vat: 472.5,
    vat_amount: 94.5,
    discount_pct: 0.25,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  {
    id: 'GF-G-DP25-5-V',
    name: 'Rice Pu Erh Toucha (витрина)',
    name_ru: null,
    category: 'Пу Эр',
    channel: 'B2C / B2B2C / E-com',
    packaging: 'Зип-лок 25г',
    weight_g: 25,
    price_rrp: 550,
    price_opt: 412.5,
    price_opt_no_vat: 343.75,
    vat_amount: 68.75,
    discount_pct: 0.25,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  {
    id: 'GF-B-GLPU357',
    name: 'Golden Tips QI ZI 2013',
    name_ru: null,
    category: 'Пу Эр Vintage',
    channel: 'B2C / B2B2C / E-com',
    packaging: 'Без переупаковки',
    weight_g: 357,
    price_rrp: 8210,
    price_opt: 6157.5,
    price_opt_no_vat: 5131.25,
    vat_amount: 1026.25,
    discount_pct: 0.25,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: 'Без упак.'
  },
  {
    id: 'GF-B-BZJPU357',
    name: 'Bang Zhang Jin Hao QI ZI 2005',
    name_ru: null,
    category: 'Пу Эр Vintage',
    channel: 'B2C / B2B2C / E-com',
    packaging: 'Без переупаковки',
    weight_g: 357,
    price_rrp: 9200,
    price_opt: 6900,
    price_opt_no_vat: 5750,
    vat_amount: 1150,
    discount_pct: 0.25,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: 'Без упак.'
  },
  {
    id: 'GF-B-ICPU357',
    name: 'Ice Island Round Cake 2018',
    name_ru: null,
    category: 'Пу Эр Vintage',
    channel: 'B2C / B2B2C / E-com',
    packaging: 'Без переупаковки',
    weight_g: 357,
    price_rrp: 12000,
    price_opt: 9000,
    price_opt_no_vat: 7500,
    vat_amount: 1500,
    discount_pct: 0.25,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: 'Без упак.'
  },
  {
    id: 'FJN-B-GAB28-AA',
    name: 'Gaba Oolong АА',
    name_ru: null,
    category: 'Технологичный',
    channel: 'B2C / B2B2C / E-com',
    packaging: 'Зип-лок 28г',
    weight_g: 28,
    price_rrp: 950,
    price_opt: 712.5,
    price_opt_no_vat: 593.75,
    vat_amount: 118.75,
    discount_pct: 0.25,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  {
    id: 'FJN-B-FLGAB28-AA',
    name: 'Flowery Gaba Oolong АА',
    name_ru: null,
    category: 'Технологичный',
    channel: 'B2C / B2B2C / E-com',
    packaging: 'Зип-лок 28г',
    weight_g: 28,
    price_rrp: 1120,
    price_opt: 840,
    price_opt_no_vat: 700,
    vat_amount: 140,
    discount_pct: 0.25,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  {
    id: 'FJN-G-MXF28',
    name: 'Fresh Air Fruit Mix',
    name_ru: null,
    category: 'Less Tea',
    channel: 'B2C / B2B2C / E-com',
    packaging: 'Зип-лок 28г',
    weight_g: 28,
    price_rrp: 560,
    price_opt: 420,
    price_opt_no_vat: 350,
    vat_amount: 70,
    discount_pct: 0.25,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  {
    id: 'FJN-G-YGT28',
    name: 'Yoga Tea',
    name_ru: null,
    category: 'Less Tea',
    channel: 'B2C / B2B2C / E-com',
    packaging: 'Зип-лок 28г',
    weight_g: 28,
    price_rrp: 672,
    price_opt: 504,
    price_opt_no_vat: 420,
    vat_amount: 84,
    discount_pct: 0.25,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  {
    id: 'FJN-G-CLD28',
    name: 'Chinese Lovers Dreams',
    name_ru: null,
    category: 'Less Tea',
    channel: 'B2C / B2B2C / E-com',
    packaging: 'Зип-лок 28г',
    weight_g: 28,
    price_rrp: 672,
    price_opt: 504,
    price_opt_no_vat: 420,
    vat_amount: 84,
    discount_pct: 0.25,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  // === ОБОРУДОВАНИЕ И ПОСУДА ===
  {
    id: 'XW-EK-CK38',
    name: 'Gooseneck электрочайник 1000мл, чёрный',
    name_ru: null,
    category: 'Чайники',
    channel: 'B2B / B2C',
    packaging: 'Без переупаковки',
    weight_g: null,
    price_rrp: 14000,
    price_opt: 14000,
    price_opt_no_vat: null,
    vat_amount: null,
    discount_pct: null,
    warehouse: 'WH-04',
    barcode: null,
    is_material: false,
    is_active: null,
    notes: '-15% / -30%'
  },
  {
    id: 'XW-EK-CK39',
    name: 'Gooseneck Luxury электрочайник 1000мл, чёрный',
    name_ru: null,
    category: 'Чайники',
    channel: 'B2B / B2C',
    packaging: 'Без переупаковки',
    weight_g: null,
    price_rrp: 17500,
    price_opt: 17500,
    price_opt_no_vat: null,
    vat_amount: null,
    discount_pct: null,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: '-15% / -25%'
  },
  {
    id: 'XW-GD-CD29',
    name: 'Иммерсивная воронка чай/кофе',
    name_ru: null,
    category: 'Воронки',
    channel: 'B2B / B2C',
    packaging: 'Без переупаковки',
    weight_g: null,
    price_rrp: 3150,
    price_opt: 3150,
    price_opt_no_vat: null,
    vat_amount: null,
    discount_pct: null,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  {
    id: 'XW-OCD-CD4W',
    name: 'Воронка Origami, белая',
    name_ru: null,
    category: 'Воронки',
    channel: 'B2B / B2C',
    packaging: 'Без переупаковки',
    weight_g: null,
    price_rrp: 2750,
    price_opt: 2750,
    price_opt_no_vat: null,
    vat_amount: null,
    discount_pct: null,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  {
    id: 'XW-OCD-CD4B',
    name: 'Воронка Origami, чёрная',
    name_ru: null,
    category: 'Воронки',
    channel: 'B2B / B2C',
    packaging: 'Без переупаковки',
    weight_g: null,
    price_rrp: 2750,
    price_opt: 2750,
    price_opt_no_vat: null,
    vat_amount: null,
    discount_pct: null,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  {
    id: 'XW-OCD-CD4R',
    name: 'Воронка Origami, красная',
    name_ru: null,
    category: 'Воронки',
    channel: 'B2B / B2C',
    packaging: 'Без переупаковки',
    weight_g: null,
    price_rrp: 2750,
    price_opt: 2750,
    price_opt_no_vat: null,
    vat_amount: null,
    discount_pct: null,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  {
    id: 'XW-SD-CD49',
    name: 'Каменная воронка 1-2 чашки (мал.)',
    name_ru: null,
    category: 'Воронки',
    channel: 'B2B / B2C',
    packaging: 'Без переупаковки',
    weight_g: null,
    price_rrp: 1950,
    price_opt: 1950,
    price_opt_no_vat: null,
    vat_amount: null,
    discount_pct: null,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  {
    id: 'XW-SD-CD50',
    name: 'Каменная воронка 1-2 чашки (бол.)',
    name_ru: null,
    category: 'Воронки',
    channel: 'B2B / B2C',
    packaging: 'Без переупаковки',
    weight_g: null,
    price_rrp: 2150,
    price_opt: 2150,
    price_opt_no_vat: null,
    vat_amount: null,
    discount_pct: null,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  {
    id: 'XW-WS-S1B',
    name: 'Подставка каменной воронки, домашняя',
    name_ru: null,
    category: 'Аксессуары',
    channel: 'B2B / B2C',
    packaging: 'Без переупаковки',
    weight_g: null,
    price_rrp: 3500,
    price_opt: 3500,
    price_opt_no_vat: null,
    vat_amount: null,
    discount_pct: null,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  {
    id: 'XW-WS-S2B',
    name: 'Подставка каменной воронки, барная',
    name_ru: null,
    category: 'Аксессуары',
    channel: 'B2B / B2C',
    packaging: 'Без переупаковки',
    weight_g: null,
    price_rrp: 5500,
    price_opt: 5500,
    price_opt_no_vat: null,
    vat_amount: null,
    discount_pct: null,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  {
    id: 'XW-MTS-WKS05W',
    name: 'Набор для матчи, белый',
    name_ru: null,
    category: 'Матча',
    channel: 'B2B / B2C',
    packaging: 'Без переупаковки',
    weight_g: null,
    price_rrp: 6050,
    price_opt: 6050,
    price_opt_no_vat: null,
    vat_amount: null,
    discount_pct: null,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  {
    id: 'XW-MTS-WKS05B',
    name: 'Набор для матчи, чёрный',
    name_ru: null,
    category: 'Матча',
    channel: 'B2B / B2C',
    packaging: 'Без переупаковки',
    weight_g: null,
    price_rrp: 6050,
    price_opt: 6050,
    price_opt_no_vat: null,
    vat_amount: null,
    discount_pct: null,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  {
    id: 'XW-WS-W1',
    name: 'Венчик для матчи',
    name_ru: null,
    category: 'Матча',
    channel: 'B2B / B2C',
    packaging: 'Без переупаковки',
    weight_g: null,
    price_rrp: 1800,
    price_opt: 1800,
    price_opt_no_vat: null,
    vat_amount: null,
    discount_pct: null,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  {
    id: 'XW-PO-PC23',
    name: 'Стеклянный чайник 600мл, серый',
    name_ru: null,
    category: 'Посуда',
    channel: 'B2B / B2C',
    packaging: 'Без переупаковки',
    weight_g: null,
    price_rrp: 2250,
    price_opt: 2250,
    price_opt_no_vat: null,
    vat_amount: null,
    discount_pct: null,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  {
    id: 'XW-PFO-FT',
    name: 'Фильтры Origami 2-4, белые, 50шт',
    name_ru: null,
    category: 'Расходники',
    channel: 'B2B / B2C',
    packaging: 'Без переупаковки',
    weight_g: null,
    price_rrp: 950,
    price_opt: 950,
    price_opt_no_vat: null,
    vat_amount: null,
    discount_pct: null,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
  {
    id: 'XW-PF-FT01',
    name: 'Фильтры V02, белые, 50шт',
    name_ru: null,
    category: 'Расходники',
    channel: 'B2B / B2C',
    packaging: 'Без переупаковки',
    weight_g: null,
    price_rrp: 650,
    price_opt: 650,
    price_opt_no_vat: null,
    vat_amount: null,
    discount_pct: null,
    warehouse: 'WH-04',
    barcode: null,
    is_material: null,
    is_active: null,
    notes: null
  },
];
