import { sqliteTable, text, integer, real } from 'drizzle-orm/sqlite-core';

export const users = sqliteTable('users', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  role: text('role').notNull(),
  pin_hash: text('pin_hash').notNull(),
  warehouse_default: text('warehouse_default'),
  created_at: integer('created_at').notNull(),
  updated_at: integer('updated_at').notNull(),
});

export const products = sqliteTable('products', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  name_ru: text('name_ru'),
  category: text('category').notNull(),
  channel: text('channel').notNull(),
  packaging: text('packaging').notNull(),
  weight_g: real('weight_g'),
  price_rrp: real('price_rrp'),
  price_opt: real('price_opt'),
  price_opt_no_vat: real('price_opt_no_vat'),
  vat_amount: real('vat_amount'),
  discount_pct: real('discount_pct'),
  warehouse: text('warehouse').notNull(),
  barcode: text('barcode'),
  is_material: integer('is_material', { mode: 'boolean' }).default(false),
  is_active: integer('is_active', { mode: 'boolean' }).default(true),
  notes: text('notes'),
  updated_at: integer('updated_at').notNull(),
  sync_pending: integer('sync_pending', { mode: 'boolean' }).default(false),
});

export const acts = sqliteTable('acts', {
  id: text('id').primaryKey(),
  number: text('number').notNull(),
  type: text('type').notNull(),
  status: text('status').notNull(),
  date: integer('date').notNull(),
  date_closed: integer('date_closed'),
  warehouse_from: text('warehouse_from'),
  warehouse_to: text('warehouse_to'),
  supplier: text('supplier'),
  invoice_number: text('invoice_number'),
  client_name: text('client_name'),
  client_contact: text('client_contact'),
  client_address: text('client_address'),
  channel: text('channel'),
  responsible_user: text('responsible_user'),
  checked_by: text('checked_by'),
  packaging_type: text('packaging_type'),
  sku_finished: text('sku_finished'),
  wc_order_id: text('wc_order_id'),
  notes: text('notes'),
  pdf_path: text('pdf_path'),
  gdrive_id: text('gdrive_id'),
  created_at: integer('created_at').notNull(),
  updated_at: integer('updated_at').notNull(),
  device_id: text('device_id').notNull(),
  sync_pending: integer('sync_pending', { mode: 'boolean' }).default(false),
});

export const act_lines = sqliteTable('act_lines', {
  id: text('id').primaryKey(),
  act_id: text('act_id').notNull(),
  line_number: integer('line_number').notNull(),
  sku: text('sku').notNull(),
  product_name: text('product_name').notNull(),
  category: text('category'),
  unit: text('unit').notNull(),
  qty_planned: real('qty_planned'),
  qty_actual: real('qty_actual'),
  qty_diff: real('qty_diff'),
  price_unit: real('price_unit'),
  amount: real('amount'),
  condition: text('condition'),
  norm_per_unit: real('norm_per_unit'),
  notes: text('notes'),
  updated_at: integer('updated_at').notNull(),
});

export const movements = sqliteTable('movements', {
  id: text('id').primaryKey(),
  date: integer('date').notNull(),
  act_id: text('act_id').notNull(),
  act_number: text('act_number').notNull(),
  operation_type: text('operation_type').notNull(),
  warehouse_from: text('warehouse_from'),
  warehouse_to: text('warehouse_to'),
  sku: text('sku').notNull(),
  product_name: text('product_name').notNull(),
  unit: text('unit').notNull(),
  qty_in: real('qty_in'),
  qty_out: real('qty_out'),
  responsible: text('responsible'),
  channel: text('channel'),
  status: text('status'),
  notes: text('notes'),
  created_at: integer('created_at').notNull(),
  device_id: text('device_id').notNull(),
  sync_pending: integer('sync_pending', { mode: 'boolean' }).default(false),
});

export const inventory_acts = sqliteTable('inventory_acts', {
  id: text('id').primaryKey(),
  number: text('number').notNull(),
  period_month: integer('period_month').notNull(),
  period_year: integer('period_year').notNull(),
  date_start: integer('date_start').notNull(),
  date_end: integer('date_end'),
  commission: text('commission'),
  status: text('status').notNull(),
  created_at: integer('created_at').notNull(),
  updated_at: integer('updated_at').notNull(),
  device_id: text('device_id').notNull(),
  sync_pending: integer('sync_pending', { mode: 'boolean' }).default(false),
  pdf_path: text('pdf_path'),
  gdrive_id: text('gdrive_id'),
});

export const inventory_lines = sqliteTable('inventory_lines', {
  id: text('id').primaryKey(),
  inventory_id: text('inventory_id').notNull(),
  sku: text('sku').notNull(),
  product_name: text('product_name').notNull(),
  warehouse: text('warehouse').notNull(),
  unit: text('unit').notNull(),
  qty_accounting: real('qty_accounting'),
  qty_actual: real('qty_actual'),
  qty_diff: real('qty_diff'),
  diff_pct: real('diff_pct'),
  reason: text('reason'),
  correction: real('correction'),
  manually_entered: integer('manually_entered', { mode: 'boolean' }).default(false),
  updated_at: integer('updated_at').notNull(),
});

export const settings = sqliteTable('settings', {
  key: text('key').primaryKey(),
  value: text('value').notNull(),
});
